language: node_js

node_js:
  - 10

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run build && mocha --mode pr; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run build && mocha --mode push; fi'
  
